chat/urls.py
from django.urls import path

from .views import all_messages_page, chat_page, make_group, on_message, all_messages_page

app_name = "chat"

urlpatterns = [
    path('get-thread/<int:pk>/', on_message, name="on-msg"),
    path("home/", all_messages_page, name="home"),
    path('chat/<int:thread_pk>/', chat_page, name="chat-page"),
    path('make-grp/', make_group, name="make-grp"),
]

login_with_face/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve
from django.conf import settings
import debug_toolbar


from customuser.api.views import MyTokenObtainPairView

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recognizer.urls', namespace='recognizer')),
    path('teacher/', include('teacher.urls', namespace='teacher')),
    path("chat/", include("chat.urls", namespace="chat")),
    
    path('api/auth/', include('dj_rest_auth.urls')),
    
    path("api/login-details/", include("login_details.api.urls")),
    path("api/basic/", include("recognizer.api.urls")),
    # path("api//", include("recognizer.api.urls")),
    
    path('api/token/', MyTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),
    
    
] 


from django.conf import settings


if settings.DEBUG:
    
    import debug_toolbar
    urlpatterns += [ path('__debug__/', include(debug_toolbar.urls)) ]
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    

recognizer/urls.py
from django.contrib import admin
from django.urls import path
from requests import delete

from .views import (
    check,
    facecam_feed,
    home_view,
    login_view,
    signup_view,
    update_profile_view,
    profile_view,
    logout_view,
    logout_confirm_view,
    login_with_face, # Login noramlly with my code # with normal function
    # login_with_face_part2, # login with recognizer Class
    # login_with_face_part3, # login with part 3 which consists of all the nessecity things inside on function!
    # test_frame
    export_users_xls,
    enable_disable_session_view,
    load_lectures,
    just_a_function,
    update_profile_image_view,
    succsess,
    delete_profile,
    lecture_details,
    load_branches, 
    load_cities, 
    load_colleges
)

app_name = 'recognizer'

urlpatterns = [
    path("check", check),
    path('', home_view, name='home'),
    path("ajax/city/", load_cities, name="city-data-url"),
    path("ajax/city/", load_colleges, name="college-data-url"),
    path("ajax/city/", load_branches, name="branch-data-url"),
    path('ajax/lec/', load_lectures, name='data_lec_url'),
    path('accounts/login/', login_view, name='login'),
    path('accounts/signup/', signup_view, name='signup'),
    path('accounts/logout/', logout_view, name='logout'),
    path('logout-confirm/', logout_confirm_view, name='logout-cnf'),
    path('profile/<int:pk>', profile_view, name='profile'),
    path('profile/<int:pk>/update', update_profile_view, name='update-profile'),
    path('profile/<int:pk>/delete', delete_profile, name='del-profile'),
    path('profile/image/<int:pk>/update', update_profile_image_view, name='update-img-profile'),
    path('login-with-face', login_with_face, name='login-with-face'),
    path('change-session', enable_disable_session_view, name='change-website'),
    path('export-attendance', export_users_xls, name='export'),
    path("succsess/", succsess, name="sus"),
    path('profile/<int:pk>/attended-lectures', lecture_details, name="stud-lectures"),
    # path('facecam-feed', facecam_feed, name='feed_stream'),
    # path('redirect-face', just_a_function, name='redirect_stream'),
    
]

teacher/urls.py
import profile
from django.contrib import admin
from django.urls import path

from .views import (
    profile_view,
    profile_list_view,
    teacher_profile_list_view,
    teacher_profile_update_view,
    update_ips,
    lecture_list_view,
    add_lecture,
    delete_lecture,
    delete_attendance,
    update_lecture,
    search_student,
    reset_confirm_view,
    reset_attendance_of_lecture,
    lec_detail,
    accept_request,
    decline_request,
    send_request,
    search_lectures,
    see_all_sessions,
    create_bulk_student,

    session_detail,
    delete_session,
    update_session,
    lecture_accepted_students_from_other_lecture,
    see_all_requests_of_session,



)


from recognizer.views import (
    accept_user_from_session,
    reject_request_to_session_view,
    remove_from_atendees_view,
)

app_name = 'teacher'


urlpatterns = [
    path('', profile_view, name='dashboard'),
    path('students/', profile_list_view, name='students-list'),
    path('teachers/', teacher_profile_list_view, name='teacher-list'),
    path('profile/update', teacher_profile_update_view, name='update-profile'),
    path('profile/update/ip', update_ips, name='ip-update'),
    path('lectures/', lecture_list_view, name='lec'),
    path('search/', search_student, name='search-stud'),
    path('search-lecture/', search_lectures, name='search-lec'),

    path('lectures/add', add_lecture, name='add-lec'),
    path('lectures/<int:pk>', lec_detail, name='lec-detail'),
    path('lectures/update/<int:pk>', update_lecture, name='lec-update'),
    path('lecture/delete/<int:pk>', delete_lecture, name='lec-delete'),
    path('attendance/delete/<int:pk>', delete_attendance, name='del-att'),
    path('reset-attendance/<int:pk>',
         reset_attendance_of_lecture, name='reset-attendance'),
    path('reset-confirm/<int:pk>', reset_confirm_view, name='reset-cnf'),

    path('lec/request/<int:pk>', send_request, name='send_request'),
    path('lec/accept/<int:user_id>/<int:lec_id>',
         accept_request, name='accept_req'),
    path('lec/decline/<int:user_id>/<int:lec_id>',
         decline_request, name='decline_req'),
    path("lec/copy/<int:from_pk>/<int:to_pk>/",
         lecture_accepted_students_from_other_lecture, name="copy-lec"),

    path("sessions-status/", see_all_sessions, name="sessions"),
    path("session/<int:pk>", session_detail, name='session-detail'),
    path("session/<int:pk>/delete", delete_session, name='session-delete'),
    path("session/<int:pk>/update", update_session, name='session-update'),
    path("sessions-requests/", see_all_requests_of_session, name='session-requests'),
    path("session/accept", accept_user_from_session, name='session-accept'),
    path("session/reject", reject_request_to_session_view, name='session-reject'),
    path("session/remove-from-accepted",
         remove_from_atendees_view, name='session-remove-accept'),


    path("create-bulk-student/", create_bulk_student, name="create-bulk-student")
]

teacher/api/views.py
from rest_framework.decorators import api_view
from rest_framework.response import Response


teacher/views.py
import io
import openpyxl
import pandas
from django.shortcuts import render, redirect, reverse
from django.contrib import messages
from django.contrib.auth.decorators import user_passes_test
from recognizer.models import SessionAttendanceModel, UserProfile, LectrueModel
from login_details.models import LoginDetails
from .forms import SessionForm, TeacherUpdateForm, LectureForm, StudentBulkForm
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from .tasks import create_student




# Create your views here.

def profile_view(request):
    context = {}
    try:
        user = request.user

        user_profile = user.user_profile

        if user.is_teacher:
            context['teacher'] = user_profile
            context['user_profile'] = user_profile
            context['sessions'] = user_profile.change_website_objects.all()
            context['lectures'] = user_profile.lectures.all()
            context['login_objects'] = user_profile.login_details_with_teacher.all(
            ).order_by('-login_date').order_by('-login_time')
        else:
            return redirect('recognizer:login')
    except Exception as e:
        print(e)
        return redirect('recognizer:logout-cnf')

    return render(request, 'teacher/index.html', context=context)


def profile_list_view(request):
    context = {}
    try:
        user = request.user
        user_profile = user.user_profile
        teacher = user_profile if user.is_teacher else None
        context['teacher'] = teacher
        context['user_profile'] = user_profile

        # teachers_user_profiles = TeacherProfileModel.objects.all().values('user')
        students = UserProfile.objects.select_related("user").filter(
            college=teacher.college, branch=teacher.branch).exclude(user__is_teacher=True)
        context['objects'] = students
        context['is_student'] = "Student"
    except Exception as e:
        print(e)
        return redirect('recognizer:logout-cnf')
    return render(request, 'teacher/students-list.html', context=context)


@user_passes_test(lambda u: u.is_staff)
def teacher_profile_list_view(request):
    context = {}
    try:
        user = request.user
        teacher = request.user.user_profile
        context['teacher'] = teacher if teacher.is_teacher else None
        context['user_profile'] = teacher

        if user.is_teacher:
            teachers = UserProfile.objects.filter(
                college=teacher.college).values('user')
            context['is_teacher'] = "Teacher"
            context['objects'] = teachers
        else:
            return redirect("recognizer:login")
    except Exception as e:
        print(e)
        return redirect('recognizer:logout-cnf')

    return render(request, 'teacher/teacher-list.html', context=context)


def teacher_profile_update_view(request):
    edit_form = None
    instance = None
    try:
        instance = request.user.user_profile
    except:
        instance = None

    edit_form = TeacherUpdateForm(request.POST or None, instance=instance)

    context = {
        'form': edit_form,
    }
    if instance.user == request.user:
        if request.POST:
            if edit_form.is_valid:
                user = edit_form.save()

                messages.success(request, "Teacher Profile Edited Sucsessfuly")
                context = {
                    'form': edit_form,
                }
                return redirect("teacher:dashboard")
            else:
                context = {
                    'form': edit_form,
                }
                messages.error(request, "Somthing is wrong ..")
                return redirect("teacher:dashboard")

    return render(request, 'teacher/update-teacher-profile.html', context=context)


def update_ips(request):
    try:
        user = request.user
        teacher = user.user_profile
        if request.POST and user.is_teacher:
            print("ohk")
            ip1 = request.POST['ip1']
            teacher.ip_address1 = ip1
            teacher.save()
            messages.success(request, "IP Updated Sucsessfuly")
            return redirect("recognizer:home")

    except:
        return redirect("recognizer:login")


def lecture_list_view(request):
    context = {}
    try:
        user = request.user
        teacher = UserProfile.objects.select_related(
            "user", "college", "branch").prefetch_related("lectures").get(user=user)
        teacher = user.user_profile
        context['teacher'] = teacher if user.is_teacher else None
        context['user_profile'] = teacher

        if user.is_teacher:
            lectures = teacher.lectures.all()
            context['objects'] = lectures

    except Exception as e:
        print(e)
        return redirect('recognizer:logout-cnf')

    return render(request, 'teacher/lectures.html', context=context)


@login_required(login_url='recognizer:login')
def lec_detail_view(request, pk=None):
    context = {}
    print(pk)
    lecture = LectrueModel.objects.prefetch_realated(
        "change_website_objects_lecture", "lecture_login_details", "accepted_user", "requested_user", "requested_user__branch_name").get(pk=pk)
    print(lecture)
    context['lecture'] = lecture
    context['user'] = request.user
    return render(request, 'teacher/lectures_detail.html', context=context)


def add_lecture(request):
    context = {}
    form = LectureForm(request.POST or None)
    context['form'] = form
    user = request.user
    user_profile = user.user_profile
    if request.POST and form.is_valid and user.is_teacher:
        teacher_profile = user_profile if user.is_teacher else None
        if teacher_profile:
            obj = form.save(commit=False)
            obj.teacher = teacher_profile
            obj.save()
            context['form'] = form
            messages.success(request, "Lecture Added Succsessfully")
            return redirect('teacher:lec')
        else:
            return redirect("recognizer:login")

    return render(request, 'teacher/update-teacher-profile.html', context=context)


def search_student(request):
    try:
        context = {}
        query = request.GET['q']
        user_profile = request.user.user_profile
        qs = UserProfile.objects.select_related("user").filter(
            Q(user__username__icontains=query) |
            Q(user__first_name__icontains=query) |
            Q(user__last_name__icontains=query) |
            Q(user__email__icontains=query) |
            Q(user__enrollment_number__icontains=query) |
            Q(phone_number__icontains=query)
        ).filter(college=user_profile.college)
        context['userprofile'] = qs.filter(user__is_teacher=False)

        teacher = qs.filter(user__is_teacher=True)
        context['teacher'] = teacher

        context['lectures'] = LectrueModel.objects.filter(Q(lecture_name__icontains=query) | Q(
            code__exact=query)).filter(college=user_profile.college)
        context['objects'] = qs
    except Exception as e:
        print(e)
        return redirect("recognizer:login")
    return render(request, "teacher/search-list.html", context)


def search_lectures(request):
    query = request.GET.get('q')
    return (request, "", {})


def session_detail(request, pk):
    context = {}
    obj = SessionAttendanceModel.objects.select_related(
        "lecture", "teacher").prefetch_related("atendees", "requested_users").get(pk=pk)
    context['session'] = obj
    return render(request, "teacher/session-detail.html", context)


def delete_session(request, pk=None):
    session = SessionAttendanceModel.objects.get(pk=pk)
    if request.user.user_profile is session.teacher:
        session.delete()
        return redirect('teacher:lec')
    else:
        return redirect("recognizer:login")


def delete_lecture(request, pk=None):
    lecture = LectrueModel.objects.get(pk=pk)
    if request.user.user_profile is lecture.teacher and lecture:
        lecture.delete()
        return redirect('teacher:lec')
    else:
        return redirect("recognizer:login")


def update_session(request, pk=None):
    context = {}
    user = request.user
    user_profile = UserProfile.objects.prefetch_related(
        "lectures").get(user=user)
    session = SessionAttendanceModel.objects.get(pk=pk)
    users = UserProfile.objects.filter(college=user_profile.college)

    form = SessionForm(request.POST or None, instance=session,
                       user_profile=users, lectures=user_profile.lectures.all())
    context["form"] = form
    if form.is_valid() and session.teacher == user_profile and user.is_teacher:
        form.save()
        context["form"] = form
        return redirect(reverse("teacher:session-detail", pk=session.pk))
    return render(request, "teacher/update-teacher-profile.html", context)


def delete_attendance(request, pk=None):
    att = LoginDetails.objects.get(pk=pk)
    if att.teacher.user is request.user:
        print('ok')
        att.delete()
        return redirect('teacher:dashboard')
    else:
        return redirect("recognizer:login")


def update_lecture(request, pk=None):
    context = {}
    lec = LectrueModel.objects.get(pk=pk)
    form = LectureForm(request.POST or None, instance=lec)
    context['form'] = form

    if lec.teacher == request.user.user_profile and form.is_valid():
        instance = form.save()
        messages.success(request, "Lecture Updated Succsessfully")
        return redirect("teacher:lec")
    return render(request, 'teacher/update-teacher-profile.html', context)


def reset_confirm_view(request, pk=None):
    context = {}
    lecture = LectrueModel.objects.get(pk=pk)
    context['view'] = 'Reset Lecture'

teacher/templates/teacher/base.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  
  <title>{% block title %}{% endblock %}</title>

  <!-- Custom fonts for this template-->
  <link href="/static/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">

  <!-- Page level plugin CSS-->
  <link href="/static/vendor/datatables/dataTables.bootstrap4.css" rel="stylesheet">

  {% block links %}
  {% endblock %}

</head>

{% block body %}
{% endblock %}

</html>

teacher/templates/teacher/bulk-create.html
{% extends 'base.html' %}


{% block body_block %}

{% for message in messages %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <b><center>{{ message }}</center> </b>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
{% endfor %}

</br>
<div class='container-sm'>
<form method='POST' class='form-control' enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input class='form-control btn btn-primary' type='submit' value='submit'>
    </br>
</form>
</div>


{% endblock %}

teacher/templates/teacher/lecture_detail.html
{% extends 'base.html' %}

{% block body_block %}
<br>
<br>
<center>
    {{ lecture }}
    <h5>
{{ lecture.lecture_name }} by {{ lecture.teacher }}
    </h5>
    <br>
    
Semester: {{ lecture.semester }} of branch {{ lecture.branch }}
<br>
<br>
</br>
<hr>
<hr>
</center>

</br>
ACCEPTED STUDENT LIST:
{% for stud in lecture.accepted_user.all %}
<a href="{{ stud.get_absolute_url }}">{{ stud.user.username }} {{ stud.email }} {{ stud.enrollment_number }} {{ stud.college }} {{ stud.branch }} </a> 
{% if user.user_profile == lecture.teacher %}
&nbsp <a href="{% url 'teacher:decline_req' user_id=stud.pk lec_id=lecture.id %}">Remove</a></br>
{% else %}{% endif %}
{% endfor %}

</br>
REQUESTED STUDENT LIST:
{% for stud in lecture.requested_user.all %}
<a href="{{ stud.get_absolute_url }}">{{ stud.user }} {{ stud.email }} {{ stud.enrollment_number }} {{ stud.branch }}</a>
{% if user.user_profile == lecture.teacher %}
<a href="{% url 'teacher:accept_req' user_id=stud.pk lec_id=lecture.id %}">Accept</a> <a href="{% url 'teacher:decline_req' user_id=stud.pk lec_id=lecture.id %}">Decline</a></br>
{% else %}{% endif %}
{% endfor %}

</br>
<hr>
<center>
    {% if user.is_teacher %}
<a href="{% url "teacher:reset-cnf" pk=lecture.pk %}">
    <button class='btn btn-danger'>Reset Attandace of Lecture</button>
</a>

<a href="{% url "teacher:lec-update" pk=lecture.pk %}">
    <button class='btn btn-success'>Update Lecture</button>
</a>


<form id="sessionForm" method='POST' action="{% url 'recognizer:change-website' %}"  data-url="{% url 'recognizer:change-website' %}">   
    {% csrf_token %}
    <input type='hidden' name='next' value={{ request.get_uri }}>
    <input type='hidden' name='lecture' value='{{ lecture.pk }}'>
    <input id="changeSession" class='mybutton vhmax {% if lecture.allow_recognize %}danger{% else %}success{% endif %}' type='submit' value='{% if lecture.allow_recognize %}Disable{% else %}Enable{% endif %} Taking Attendance of {{lecture.lecture_name}}, code: {{ lecture.code }}' name='submit'>
</form>

</center>


{% for session in lecture.change_website_objects_lecture.all %}
{% if forloop.first %}
<h1>Sessions of the lecture </h1>
{% else %}{% endif %}
<a href="{% url 'teacher:session-detail' pk=session.pk %}"><b>{{ session }}</b></a>
<br>
{% endfor %}
{% else %}

<center>
{% if user.user_profile in lecture.requested_user.all or user.user_profile in lecture.accepted_user.all %}
request sent
{% else %} <a href="{% url 'teacher:send_request' pk=lecture.pk %}"><button class='btn btn-dark'> Send request</button></a> {% endif %}

{% endif %}
</center>

{% endblock %}

teacher/templates/teacher/lectures.html
{% extends 'base.html' %}

{% block body_block %}
{% for message in messages %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  {{ message }}
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
{% endfor %}


{% for object in objects %}
<center>
<div class="col-md-8">
    
    <div class="card mb-3">
        
      <div class="card-body">
        <div class="row">
          <br>
          <center>
              <b><h4> Lecture by {{ object.teacher.user.username | upper }}</b></h4>
              {{ teacher.username }}
              {{ teacher.college }}
              {{ teacher.branch }}
              </center>
              <br>
          
          <hr>
          <br>
          <div class="col-sm-3">
            <h6 class="mb-0">Lecture</h6>
          </div>
          <div class="col-sm-9 text-secondary">
            <a href="{% url "teacher:lec-detail" pk=object.pk %}">{{ object.lecture_name }}</a> of Branch: {{ object.branch }}, Semester: {{ object.semester }} </a> &nbsp&nbsp
            <a "padding-left:30px;" href="{% url 'teacher:lec-update' pk=object.pk %}">Update</a>
            <a style="float:right;" href={{ object.get_delete_url }}><b><font color='red'> X </font></b></a>
          </div>
        </div>
    </div>
</div>
</div>
        <hr>

{% endfor %}


{% endblock %}

teacher/templates/teacher/requests.html
{% extends 'base.html' %}

{% block body_block %}

{% for message in messages %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  {{ message }}
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
{% endfor %}


{% if requests.change_website_objects %}
{% for session in requests.change_website_objects.all %}
    {% if forloop.first %}
    <b><h4> Requests List</b></h4>
    {% else%}{% endif %}
    {% if session.requested_user %}
    {% for up in session.requested_user %}
        {% if forloop.first %}
        Session : {{ session.name }} - on {{ session.timestamp }}
        {% else %}{% endif %}

        <center>
        <div class="col-md-8">
            
            <div class="card mb-3">
                
            <div class="card-body">
                <div class="row">
                    
                <div class="col-sm-3">
                    <h6 class="mb-0">{{ up.user.username }}</h6>
                </div>
                <div class="col-sm-9 text-secondary">
                    <a href={{ up.get_absolute_url }}>{{ up }} </a>
                </div>

                <a href="{% url 'teacher:accept_req' user_id=stud.pk lec_id=lecture.id %}">Accept</a> <a href="{% url 'teacher:decline_req' user_id=stud.pk lec_id=lecture.id %}">Decline</a></br>
            
                </div>
            </div>
        </div>
        </div>
                <hr>
        {% endfor %}
        {% endif %}
{% endfor %}
{% endif %}


    


        


{% endblock %}

teacher/templates/teacher/reset-cnf.html
{% extends 'base.html' %} 

{% block body_block %}
<center>
<br>
</br>
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
  {{ view }} Attandace ??
</button>
</center>
<br>
<hr>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">{{ view }} ??</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Reseting all Attandance of Lecture {{ lecture }}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <a href="{% url 'teacher:reset-attendance' pk=lecture.pk %}"><button type="button" class="btn btn-danger"}>Confirm</button>
      </div>
    </div>
  </div>
</div>

{% endblock %}

teacher/templates/teacher/session-detail.html
{% extends 'base.html' %}

{% block body_block %}
<br>
<br>
<center>
    {{ session }}
    <h5>
Session of {{ session.lecture.lecture_name }} by {{ session.teacher }}
    </h5>
    <br>
    
Session Semester: {{ session.lecture.semester }} of branch {{ session.lecture.branch }}
<br>
<br>
</br>
<hr>
<hr>
</center>

</br>
Presesnt Student List in session:
{% for stud in lecture.atendees.all %}
<a href="{{ stud.get_absolute_url }}">{{ stud.user.username }} {{ stud.email }} {{ stud.enrollment_number }} {{ stud.college }} {{ stud.branch }} </a> 
{% if user.user_profile == lecture.teacher %}
&nbsp <a href="{% url 'teacher:decline_req' user_id=stud.pk lec_id=lecture.id %}">Remove</a></br>
{% else %}{% endif %}
{% endfor %}

</br>


Requested Student List:
{% for stud in lecture.requested_users.all %}
<a href="{{ stud.get_absolute_url }}">{{ stud.user }} {{ stud.email }} {{ stud.enrollment_number }} {{ stud.branch }}</a>
{% if user.user_profile == lecture.teacher %}
<a href="{% url 'teacher:accept_req' user_id=stud.pk lec_id=lecture.id %}">Accept</a> <a href="{% url 'teacher:decline_req' user_id=stud.pk lec_id=lecture.id %}">Decline</a></br>
{% else %}{% endif %}
{% endfor %}

</br>
<hr>
<center>
    {% if user.is_teacher %}
<a href="{% url "teacher:session-delete" pk=session.pk %}">
    <button class='btn btn-danger'>Delete Session and Attendance</button>
</a>

<a href="{% url "teacher:session-update" pk=session.pk %}">
    <button class='btn btn-success'>Update Session</button>
</a>


<form id="sessionForm" method='POST' action="{% url 'recognizer:change-website' %}"  data-url="{% url 'recognizer:change-website' %}">   
    {% csrf_token %}
    <input type='hidden' name='next' value={{ request.get_uri }}>
    <input type='hidden' name='lecture' value='{{ lecture.pk }}'>
    <input id="changeSession" class='mybutton vhmax {% if lecture.allow_recognize %}danger{% else %}success{% endif %}' type='submit' value='{% if lecture.allow_recognize %}Disable{% else %}Enable{% endif %} Taking Attendance of {{lecture.lecture_name}}, code: {{ lecture.code }}' name='submit'>
</form>


{% else %}

{% if user.user_profile in lecture.requested_user.all or user.user_profile in lecture.accepted_user.all %}
request sent
{% else %} <a href="{% url 'teacher:send_request' pk=lecture.pk %}"><button class='btn btn-dark'> Send request</button></a> {% endif %}

{% endif %}
</center>

{% endblock %}

teacher/templates/teacher/sessions.html
{% extends "teacher/base.html" %}
{% load static %}
{% block title %}Teacher Dashboard{% endblock %}

{% block links %}
  <!-- Custom styles for this template-->
  <link href="{% static 'css/sb-admin.css' %}" rel="stylesheet">
{% endblock %}



{% block body %}




{% for lec in lectures %}
<div class="col-xl-3 col-sm-6 mb-3">
    <div class="card text-white bg-warning o-hidden h-100">
      <div class="card-body">
        <div class="card-body-icon">
          <i class="fas fa-fw fa-shopping-cart"></i>
        </div>
        <div class="mr-5">{{ lec.lecture_name }}
          {% if lec.allow_recognize %}
            <div class="mr-5">Students Can Take Attendance</div>
                {% else %}
                <div class="mr-5">Students Can't Take Attendance</div>
            {% endif %}
        </div>
      </div>
      <form method='POST' id='myForm{{lec.id}}' action="{% url 'recognizer:change-website' %}">
        <input type='hidden' name='next' value="{{ request.get_full_path }}">
        <input type='hidden' name="lecture" value={{ lec.pk }}>
        {% csrf_token %}
      </form>
      <a class="card-footer text-white clearfix small z-1" onclick="document.getElementById('myForm{{lec.id}}').submit();">
        <span class="float-left">Change</span>
        <span class="float-right">
          <i class="fas fa-angle-right"></i>
        </span>
      </a>
    </div>
  </div>
  {% endfor %}

  {% endblock %}