chat/urls.py
from django.urls import path

from .views import all_messages_page, chat_page, make_group, on_message, all_messages_page

app_name = "chat"

urlpatterns = [
    path('get-thread/<int:pk>/', on_message, name="on-msg"),
    path("home/", all_messages_page, name="home"),
    path('chat/<int:thread_pk>/', chat_page, name="chat-page"),
    path('make-grp/', make_group, name="make-grp"),
]

login_with_face/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve
from django.conf import settings
import debug_toolbar


from customuser.api.views import MyTokenObtainPairView

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recognizer.urls', namespace='recognizer')),
    path('teacher/', include('teacher.urls', namespace='teacher')),
    path("chat/", include("chat.urls", namespace="chat")),
    
    path('api/auth/', include('dj_rest_auth.urls')),
    
    path("api/login-details/", include("login_details.api.urls")),
    path("api/basic/", include("recognizer.api.urls")),
    # path("api//", include("recognizer.api.urls")),
    
    path('api/token/', MyTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),
    
    
] 


from django.conf import settings


if settings.DEBUG:
    
    import debug_toolbar
    urlpatterns += [ path('__debug__/', include(debug_toolbar.urls)) ]
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    

recognizer/urls.py
from django.contrib import admin
from django.urls import path
from requests import delete

from .views import (
    check,
    facecam_feed,
    home_view,
    login_view,
    signup_view,
    update_profile_view,
    profile_view,
    logout_view,
    logout_confirm_view,
    login_with_face, # Login noramlly with my code # with normal function
    # login_with_face_part2, # login with recognizer Class
    # login_with_face_part3, # login with part 3 which consists of all the nessecity things inside on function!
    # test_frame
    export_users_xls,
    enable_disable_session_view,
    load_lectures,
    just_a_function,
    update_profile_image_view,
    succsess,
    delete_profile,
    lecture_details,
    load_branches, 
    load_cities, 
    load_colleges
)

app_name = 'recognizer'

urlpatterns = [
    path("check", check),
    path('', home_view, name='home'),
    path("ajax/city/", load_cities, name="city-data-url"),
    path("ajax/city/", load_colleges, name="college-data-url"),
    path("ajax/city/", load_branches, name="branch-data-url"),
    path('ajax/lec/', load_lectures, name='data_lec_url'),
    path('accounts/login/', login_view, name='login'),
    path('accounts/signup/', signup_view, name='signup'),
    path('accounts/logout/', logout_view, name='logout'),
    path('logout-confirm/', logout_confirm_view, name='logout-cnf'),
    path('profile/<int:pk>', profile_view, name='profile'),
    path('profile/<int:pk>/update', update_profile_view, name='update-profile'),
    path('profile/<int:pk>/delete', delete_profile, name='del-profile'),
    path('profile/image/<int:pk>/update', update_profile_image_view, name='update-img-profile'),
    path('login-with-face', login_with_face, name='login-with-face'),
    path('change-session', enable_disable_session_view, name='change-website'),
    path('export-attendance', export_users_xls, name='export'),
    path("succsess/", succsess, name="sus"),
    path('profile/<int:pk>/attended-lectures', lecture_details, name="stud-lectures"),
    # path('facecam-feed', facecam_feed, name='feed_stream'),
    # path('redirect-face', just_a_function, name='redirect_stream'),
    
]

teacher/urls.py
import profile
from django.contrib import admin
from django.urls import path

from .views import (
    profile_view,
    profile_list_view,
    teacher_profile_list_view,
    teacher_profile_update_view,
    update_ips,
    lecture_list_view,
    add_lecture,
    delete_lecture,
    delete_attendance,
    update_lecture,
    search_student,
    reset_confirm_view,
    reset_attendance_of_lecture,
    lec_detail,
    accept_request,
    decline_request,
    send_request,
    search_lectures,
    see_all_sessions,
    create_bulk_student,

    session_detail,
    delete_session,
    update_session,
    lecture_accepted_students_from_other_lecture,
    see_all_requests_of_session,



)


from recognizer.views import (
    accept_user_from_session,
    reject_request_to_session_view,
    remove_from_atendees_view,
)

app_name = 'teacher'


urlpatterns = [
    path('', profile_view, name='dashboard'),
    path('students/', profile_list_view, name='students-list'),
    path('teachers/', teacher_profile_list_view, name='teacher-list'),
    path('profile/update', teacher_profile_update_view, name='update-profile'),
    path('profile/update/ip', update_ips, name='ip-update'),
    path('lectures/', lecture_list_view, name='lec'),
    path('search/', search_student, name='search-stud'),
    path('search-lecture/', search_lectures, name='search-lec'),

    path('lectures/add', add_lecture, name='add-lec'),
    path('lectures/<int:pk>', lec_detail, name='lec-detail'),
    path('lectures/update/<int:pk>', update_lecture, name='lec-update'),
    path('lecture/delete/<int:pk>', delete_lecture, name='lec-delete'),
    path('attendance/delete/<int:pk>', delete_attendance, name='del-att'),
    path('reset-attendance/<int:pk>',
         reset_attendance_of_lecture, name='reset-attendance'),
    path('reset-confirm/<int:pk>', reset_confirm_view, name='reset-cnf'),

    path('lec/request/<int:pk>', send_request, name='send_request'),
    path('lec/accept/<int:user_id>/<int:lec_id>',
         accept_request, name='accept_req'),
    path('lec/decline/<int:user_id>/<int:lec_id>',
         decline_request, name='decline_req'),
    path("lec/copy/<int:from_pk>/<int:to_pk>/",
         lecture_accepted_students_from_other_lecture, name="copy-lec"),

    path("sessions-status/", see_all_sessions, name="sessions"),
    path("session/<int:pk>", session_detail, name='session-detail'),
    path("session/<int:pk>/delete", delete_session, name='session-delete'),
    path("session/<int:pk>/update", update_session, name='session-update'),
    path("sessions-requests/", see_all_requests_of_session, name='session-requests'),
    path("session/accept", accept_user_from_session, name='session-accept'),
    path("session/reject", reject_request_to_session_view, name='session-reject'),
    path("session/remove-from-accepted",
         remove_from_atendees_view, name='session-remove-accept'),


    path("create-bulk-student/", create_bulk_student, name="create-bulk-student")
]

templates/snippets/email_template.html
username: {{ username }} 
email: {{ email }} 
enrollment_number: {{ enrollment_number }} 
college: {{ college }} 
branch: {{ branch }} 
password: {{ password }} 

templates/snippets/navbar.html
{% load static %}
<nav>
  
</nav>
<nav class="navbar sticky-top fixed-top navbar-expand-lg navbar-dark" style="background-color:#4056a1;color:black">
  <div class="container-fluid">
  <a class="navbar-brand" href="{% url 'recognizer:home' %}">
  <img src="{% static 'images/favicon.png' %%}" width="30" height="30" class="d-inline-block align-center" alt="">
   <span class="navbar-brand mb-0 h1" style="color:#white;">LogUP</span></a>
   <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto mb-2 mb-lg-">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'recognizer:home' %}">Home <span class="sr-only"></span></a>
      </li>


      
      <li class="nav-item active">
        {% if upk %}
          <a class="nav-link" href="{% url 'recognizer:profile' pk=upk %}">See Profile</a>
        {% else %} {% endif %}  
      </li>


      {% if request.user.is_teacher %}
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'teacher:dashboard' %}">Dashboard</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'teacher:session-requests' %}">Session Requests</a>
        </li>
      {% else %} {% endif %}

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          Account
        </a>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
          {% if not request.user.is_authenticated %}
            <li><a class="dropdown-item" href="{% url 'recognizer:login' %}">Login</a></li>
            <li><a class="dropdown-item" href="{% url 'recognizer:signup' %}">Sign-Up</a></li>
          {% else %}
          <li>
          <form class="d-flex" method='GET' action="{% url 'teacher:search-lec' %}">
            <input class="form-control" type="search" name='q' placeholder="Lecture Search" aria-label="Search" value='{{ request.GET.q }}' >
            <button class="btn btn-fill" type="submit" >Search</button>
          </form>
          <li>
            <li><a class="dropdown-item" href="{% url 'recognizer:logout-cnf' %}">Logout</a></li>
          {% endif %}
            <div class="dropdown-divider"></div>
        </ul>
      </li>
       
    </ul>

    <form class="d-flex" method='GET' action="{% url 'teacher:search-stud' %}">
      <input class="form-control" type="search" name='q' placeholder="Search" aria-label="Search" value='{{ request.GET.q }}' style="margin-left:2px;border-color:#d79922;color:#d79922;">
      <button class="mybutton smallbutton" type="submit" >Search</button>
    </form>
  </div>
</div>
</nav>