chat/urls.py
from django.urls import path

from .views import all_messages_page, chat_page, make_group, on_message, all_messages_page

app_name = "chat"

urlpatterns = [
    path('get-thread/<int:pk>/', on_message, name="on-msg"),
    path("home/", all_messages_page, name="home"),
    path('chat/<int:thread_pk>/', chat_page, name="chat-page"),
    path('make-grp/', make_group, name="make-grp"),
]

login_with_face/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve
from django.conf import settings
import debug_toolbar


from customuser.api.views import MyTokenObtainPairView

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recognizer.urls', namespace='recognizer')),
    path('teacher/', include('teacher.urls', namespace='teacher')),
    path("chat/", include("chat.urls", namespace="chat")),
    
    path('api/auth/', include('dj_rest_auth.urls')),
    
    path("api/login-details/", include("login_details.api.urls")),
    path("api/basic/", include("recognizer.api.urls")),
    # path("api//", include("recognizer.api.urls")),
    
    path('api/token/', MyTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),
    
    
] 


from django.conf import settings


if settings.DEBUG:
    
    import debug_toolbar
    urlpatterns += [ path('__debug__/', include(debug_toolbar.urls)) ]
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    

recognizer/api/urls.py
from django.urls import path
from graphene_django.views import GraphQLView

from recognizer.api.schema import schema
from recognizer.api.views import (
    LecturesListAPI,
    UserProfileListView,
    UserProfileDetailUpdateDelete,
    enable_disable_session_api_view,
    main_form_submit_API_view,
    LecturesListAPI,
    LectureRetriveDestroyUpdateAPIView,
    SessionListAPI,
    SessionDetailUpdateDestroyAPIView,
    CitesListView,
    CollegesListView,
    BranchListView,
    update_ips,
    accept_user_from_session_api_view,
    reject_request_to_session_api_view,
    remove_from_atendees_api_view,
    lecture_accepted_students_from_other_lecture,
)
# from .views import UserProfileViewset
# from rest_framework.routers import DefaultRouter

# router = DefaultRouter()
# router.register(r'users', UserProfileViewset, basename='userprofile')
urlpatterns = [
    path('user/list/', UserProfileListView.as_view()),
    path('user/<int:pk>/', UserProfileDetailUpdateDelete.as_view()),
    path('enable-disable-session/', enable_disable_session_api_view),
    path('lecture/list', LecturesListAPI.as_view()),
    path('lecture/<int:pk>', LectureRetriveDestroyUpdateAPIView.as_view()),
    path('session/list', SessionListAPI.as_view()),
    path('session/<int:pk>', SessionDetailUpdateDestroyAPIView.as_view()),
    path('cities/list', CitesListView.as_view()),
    path('colleges/list', CollegesListView.as_view()),
    path('branches/list', BranchListView.as_view()),
    path('update-ip/', update_ips),
    path('session/accept/attendee', accept_user_from_session_api_view),
    path('session/reject/attendee', reject_request_to_session_api_view),
    path('session/remove/request', remove_from_atendees_api_view),
    path("lecture/copy/<int:from_pk>/<int:to_pk>/", lecture_accepted_students_from_other_lecture),
]

recognizer/urls.py
from django.contrib import admin
from django.urls import path
from requests import delete

from .views import (
    check,
    facecam_feed,
    home_view,
    login_view,
    signup_view,
    update_profile_view,
    profile_view,
    logout_view,
    logout_confirm_view,
    login_with_face, # Login noramlly with my code # with normal function
    # login_with_face_part2, # login with recognizer Class
    # login_with_face_part3, # login with part 3 which consists of all the nessecity things inside on function!
    # test_frame
    export_users_xls,
    enable_disable_session_view,
    load_lectures,
    just_a_function,
    update_profile_image_view,
    succsess,
    delete_profile,
    lecture_details,
    load_branches, 
    load_cities, 
    load_colleges
)

app_name = 'recognizer'

urlpatterns = [
    path("check", check),
    path('', home_view, name='home'),
    path("ajax/city/", load_cities, name="city-data-url"),
    path("ajax/city/", load_colleges, name="college-data-url"),
    path("ajax/city/", load_branches, name="branch-data-url"),
    path('ajax/lec/', load_lectures, name='data_lec_url'),
    path('accounts/login/', login_view, name='login'),
    path('accounts/signup/', signup_view, name='signup'),
    path('accounts/logout/', logout_view, name='logout'),
    path('logout-confirm/', logout_confirm_view, name='logout-cnf'),
    path('profile/<int:pk>', profile_view, name='profile'),
    path('profile/<int:pk>/update', update_profile_view, name='update-profile'),
    path('profile/<int:pk>/delete', delete_profile, name='del-profile'),
    path('profile/image/<int:pk>/update', update_profile_image_view, name='update-img-profile'),
    path('login-with-face', login_with_face, name='login-with-face'),
    path('change-session', enable_disable_session_view, name='change-website'),
    path('export-attendance', export_users_xls, name='export'),
    path("succsess/", succsess, name="sus"),
    path('profile/<int:pk>/attended-lectures', lecture_details, name="stud-lectures"),
    # path('facecam-feed', facecam_feed, name='feed_stream'),
    # path('redirect-face', just_a_function, name='redirect_stream'),
    
]

teacher/urls.py
import profile
from django.contrib import admin
from django.urls import path

from .views import (
    profile_view,
    profile_list_view,
    teacher_profile_list_view,
    teacher_profile_update_view,
    update_ips,
    lecture_list_view,
    add_lecture,
    delete_lecture,
    delete_attendance,
    update_lecture,
    search_student,
    reset_confirm_view,
    reset_attendance_of_lecture,
    lec_detail,
    accept_request,
    decline_request,
    send_request,
    search_lectures,
    see_all_sessions,
    create_bulk_student,

    session_detail,
    delete_session,
    update_session,
    lecture_accepted_students_from_other_lecture,
    see_all_requests_of_session,



)


from recognizer.views import (
    accept_user_from_session,
    reject_request_to_session_view,
    remove_from_atendees_view,
)

app_name = 'teacher'


urlpatterns = [
    path('', profile_view, name='dashboard'),
    path('students/', profile_list_view, name='students-list'),
    path('teachers/', teacher_profile_list_view, name='teacher-list'),
    path('profile/update', teacher_profile_update_view, name='update-profile'),
    path('profile/update/ip', update_ips, name='ip-update'),
    path('lectures/', lecture_list_view, name='lec'),
    path('search/', search_student, name='search-stud'),
    path('search-lecture/', search_lectures, name='search-lec'),

    path('lectures/add', add_lecture, name='add-lec'),
    path('lectures/<int:pk>', lec_detail, name='lec-detail'),
    path('lectures/update/<int:pk>', update_lecture, name='lec-update'),
    path('lecture/delete/<int:pk>', delete_lecture, name='lec-delete'),
    path('attendance/delete/<int:pk>', delete_attendance, name='del-att'),
    path('reset-attendance/<int:pk>',
         reset_attendance_of_lecture, name='reset-attendance'),
    path('reset-confirm/<int:pk>', reset_confirm_view, name='reset-cnf'),

    path('lec/request/<int:pk>', send_request, name='send_request'),
    path('lec/accept/<int:user_id>/<int:lec_id>',
         accept_request, name='accept_req'),
    path('lec/decline/<int:user_id>/<int:lec_id>',
         decline_request, name='decline_req'),
    path("lec/copy/<int:from_pk>/<int:to_pk>/",
         lecture_accepted_students_from_other_lecture, name="copy-lec"),

    path("sessions-status/", see_all_sessions, name="sessions"),
    path("session/<int:pk>", session_detail, name='session-detail'),
    path("session/<int:pk>/delete", delete_session, name='session-delete'),
    path("session/<int:pk>/update", update_session, name='session-update'),
    path("sessions-requests/", see_all_requests_of_session, name='session-requests'),
    path("session/accept", accept_user_from_session, name='session-accept'),
    path("session/reject", reject_request_to_session_view, name='session-reject'),
    path("session/remove-from-accepted",
         remove_from_atendees_view, name='session-remove-accept'),


    path("create-bulk-student/", create_bulk_student, name="create-bulk-student")
]

recognizer/forms.py
from django import forms

from login_details.models import LoginDetails

from .models import LectrueModel, UserProfile

class UserCreateForm(forms.Form):
    username = forms.CharField()
    email = forms.EmailField(required=False)
    enrollment_number = forms.NumberInput()
    gender = forms.CharField(max_length=1)
    password = forms.CharField(widget=forms.PasswordInput)
    
    def __init__(self, *args, **kwargs):
        super(AuthenticationForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
    

class AuthenticationForm(forms.Form):
    username = forms.CharField()
    email = forms.EmailField(required=False)
    password = forms.CharField(widget=forms.PasswordInput)
    
        
    
    def __init__(self, *args, **kwargs):
        super(AuthenticationForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
        
        
        
class FirstTimeUserProfileForm(forms.ModelForm):
    birth_date = forms.DateField(widget = forms.SelectDateWidget())
    class Meta():
        model = UserProfile
        fields = ['image', 'enrollment_number', 'about', 'gender', 'birth_date',
                  'phone_number', 'website', 'github_username',
                  'twitter_handle', 'instagram_username', 'facebook_username', "college", "company", "branch", "city","district", "semester"]

        
    def __init__(self, *args, **kwargs):
        super(FirstTimeUserProfileForm, self).__init__(*args, **kwargs)
        self.fields['enrollment_number'].required = True
        self.fields['college'].required = True
        self.fields['branch'].required = True
        self.fields['semester'].required = True
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
            
class SecondTimeUserProfileForm(forms.ModelForm):
    birth_date = forms.DateField(widget = forms.SelectDateWidget())
    class Meta():
        model = UserProfile 
        fields = ['about', 'birth_date',
                  'phone_number', 'website', 'github_username',
                  'twitter_handle', 'instagram_username', 'facebook_username']

        
    def __init__(self, *args, **kwargs):
        super(SecondTimeUserProfileForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
            
class UserProfileImageForm(forms.ModelForm):

    class Meta():
        model = UserProfile
        fields = ['image', 'enrollment_number', "college", "company", "branch", "city","district", "semester"]
    
    def __init__(self, *args, **kwargs):
        super(UserProfileImageForm, self).__init__(*args, **kwargs)
        self.fields['enrollment_number'].required = True
        self.fields['college'].required = True
        self.fields['branch'].required = True
        self.fields['semester'].required = True
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
    
            
class LectureDetailsForm(forms.ModelForm):
    
    class Meta():
        model = LoginDetails
        fields = ['teacher', 'lecture']
    
    def __init__(self, *args, **kwargs):
        self.user_profile = kwargs.pop('user_profile')
        
        
        super().__init__(*args, **kwargs)
        self.fields['teacher'].required = True
        self.fields['lecture'].required = True
        user_p = UserProfile.objects.prefetch_related("user").filter(college=self.user_profile.college, branch=self.user_profile.branch, user__is_teacher=True)
        self.fields['teacher'].queryset = user_p
        self.fields['teacher'].widget.attrs.update({'class':'form-control', 'required':'true'})
        self.fields['lecture'].widget.attrs.update({'class':'form-control'})
    
        self.fields['lecture'].queryset = LectrueModel.objects.none()

        
        if 'teacher' in self.data:
            try:
                teacher_id = int(self.data.get('teacher'))
                
                self.fields['lecture'].queryset =LectrueModel.objects.filter(teacher_id=teacher_id).order_by('-id')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['lecture'].queryset = self.instance.teacher.lectures.order_by('-id')

            
            
    

recognizer/templates/recognizer/anything-confirm.html
 {% extends 'base.html' %} 

{% block body_block %}
<center>
<br>
</br>
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
  {{ view }} ??
</button>
</center>
<br>
<hr>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">{{ view }} ??</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        once you logged out you have again recognize your face!
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <a href="{% url 'recognizer:logout' %}"><button type="button" class="btn btn-primary"}>LogOut??</button>
      </div>
    </div>
  </div>
</div>

{% endblock %}

recognizer/templates/recognizer/feed-stream.html
<img src="{% url 'recognizer:feed_stream' %}" >

recognizer/templates/recognizer/lecture_dropdown_list_option.html
<option value="">---------</option>
{% for lec in lectures %}
<option value="{{ lec.pk }}">{{ lec.lecture_name }}</option>
{% endfor %}

recognizer/templates/recognizer/lectures-details.html
{% extends 'base.html' %}

{% block body_block%}
<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>

<div class='container-fluid'>
    {% for lec, time in lectures_name %}
    {{ lec }} : {{ time }} lecture/s attended
    <br>
    {% endfor %}
    </div>

<div class='container-fluid'>
{% autoescape off %}
{{ plot_div }}
{% endautoescape %}
<div>
<hr>
<br>



{% endblock %}

recognizer/templates/recognizer/load_branches.html
<option value="">---------</option>
{% for br in branches %}
<option value="{{ lec.pk }}">{{ lec.lecture_name }}</option>
{% endfor %}

recognizer/templates/recognizer/load_cities.html
<option value="">---------</option>
{% for lec in lectures %}
<option value="{{ lec.pk }}">{{ lec.lecture_name }}</option>
{% endfor %}

recognizer/templates/recognizer/load_colleges.html
<option value="">---------</option>
{% for lec in lectures %}
<option value="{{ lec.pk }}">{{ lec.lecture_name }}</option>
{% endfor %}

recognizer/templates/recognizer/load_district.html
<option value="">---------</option>
{% for lec in lectures %}
<option value="{{ lec.pk }}">{{ lec.lecture_name }}</option>
{% endfor %}

recognizer/templates/recognizer/login.html
{% extends 'base.html' %}

{% block body_block %}
{% for message in messages %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <b><center>{{ message }}</center> </b>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
{% endfor %}

<center> <h1> Login </h1>

<p> dont have account, Ask your Teacher to create account <a href="{% url 'recognizer:signup' %}"> Create Account</a></center>
<div class='container-sm'>
<form class='form-control' method='POST' >
    {% csrf_token %}
    {{ form.as_p }}
    <input type="hidden" name="next" value="{{ request.GET.next }}"/>
    <input type='submit' class='btn btn-dark'>
</form>
</div>



{% endblock %}

recognizer/templates/recognizer/profile.html
{% extends 'base.html' %}

{% block body_block %}

{% for message in messages %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <b><center>{{ message }}</center> </b>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
{% endfor %}
{{ object }}
{% if object %}
<div class="container">
    <div class="main-body">
    
          <!-- Breadcrumb -->
          <nav aria-label="breadcrumb" class="main-breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="{% url 'recognizer:home' %}">Home</a></li>
              <li class="breadcrumb-item"><a href="javascript:void(0)">User</a></li>
              <li class="breadcrumb-item active" aria-current="page">User Profile</li>
            </ol>
          </nav>
          <!-- /Breadcrumb -->
    {{ object.img.url }}
          <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
              <div class="card">
                <div class="card-body">
                  <div class="d-flex flex-column align-items-center text-center">
                    <img src={% if object.image %}"{{ object.image.url }}"{% else %}"#"{% endif %} alt="Admin" class="rounded-circle" width="150">
                    <div class="mt-3">
                      <h4>{{ object.user.username }}</h4>
                      {% if teacher %}
                      Teacher
                        {% else %}{% endif %}
                      <p>{{ object.user.email }}</p>
          
                      <p class="text font-size-sm">{{ object.about }}</p>
                      <a href="{% url "chat:on-msg" pk=object.pk %}"><button class="btn btn-primary">Message</button></a>
                      <a href="{% url "recognizer:stud-lectures" pk=object.pk %}"><button class="btn btn-outline-primary">See Attandance Details</button> </a>
                    </div>
                  </div>
                </div>
              </div>
              <div class="card mt-3">
                <ul class="list-group list-group-flush">
                  <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                    <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-globe mr-2 icon-inline"><circle cx="12" cy="12" r="10"></circle><line x1="2" y1="12" x2="22" y2="12"></line><path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"></path></svg>Website</h6>
                    <span class="text-secondary">{{ object.website }}</span>
                  </li>
                  <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                    <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-github mr-2 icon-inline"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path></svg>Github</h6>
                    <span class="text-secondary">{{ object.github_username }}</span>
                  </li>
                  <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                    <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-twitter mr-2 icon-inline text-info"><path d="M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z"></path></svg>Twitter</h6>
                    <span class="text-secondary">{{ object.twitter_handle }}</span>
                  </li>
                  <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                    <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-instagram mr-2 icon-inline text-danger"><rect x="2" y="2" width="20" height="20" rx="5" ry="5"></rect><path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"></path><line x1="17.5" y1="6.5" x2="17.51" y2="6.5"></line></svg>Instagram</h6>
                    <span class="text-secondary">{{ object.instagram_username }}</span>
                  </li>
                  <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                    <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-facebook mr-2 icon-inline text-primary"><path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z"></path></svg>Facebook</h6>
                    <span class="text-secondary">{{ object.facebook_username }}</span>
                  </li>
                </ul>
              </div>
            </div>
            <div class="col-md-8">
              <div class="card mb-3">
                <div class="card-body">
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Full Name</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{ object.user.first_name }}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Email</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{ object.user.email }}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Phone</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{ object.phone_number }}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">About</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{ object.about }}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">College</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{ object.college }}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Branch</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{ object.branch }}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Enroll Number</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{ object.enrollment_number }}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Birth Date</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{ object.birth_date }}
                    </div>
                  </div>
                </div>
              </div>
              <div class="row gutters-sm">
                <div class="col-lg-12 mb-3">
                  <div class="card h-100">
                    <div class="card-body">
                    <p><span><i>Login Details</i></span></p>

                      <ul class="list-group">
                      {% for login in login_object %}
                        <li class="list-group-item">Lecture {{ login.lecture}} by {{login.teacher}} on {{ login.login_date }} |  {{ login.login_time }}</li>
                      </ul>
                      {% endfor %}

                    </div>
                  </div>
                </div>
                {% comment %} <div class="col-sm-6 mb-3">
                  <div class="card h-100">
                    <div class="card-body">
                      <h6 class="d-flex align-items-center mb-3"><i class="material-icons text-info mr-2">assignment</i>Project Status</h6>
                      <small>Web Design</small>
                      <div class="progress mb-3" style="height: 5px">
                        <div class="progress-bar bg-primary" role="progressbar" style="width: 80%" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100"></div>
                      </div>
                      <small>Website Markup</small>
                      <div class="progress mb-3" style="height: 5px">
                        <div class="progress-bar bg-primary" role="progressbar" style="width: 72%" aria-valuenow="72" aria-valuemin="0" aria-valuemax="100"></div>
                      </div>
                      <small>One Page</small>
                      <div class="progress mb-3" style="height: 5px">
                        <div class="progress-bar bg-primary" role="progressbar" style="width: 89%" aria-valuenow="89" aria-valuemin="0" aria-valuemax="100"></div>
                      </div>
                      <small>Mobile Template</small>
                      <div class="progress mb-3" style="height: 5px">
                        <div class="progress-bar bg-primary" role="progressbar" style="width: 55%" aria-valuenow="55" aria-valuemin="0" aria-valuemax="100"></div>
                      </div>
                      <small>Backend API</small>
                      <div class="progress mb-3" style="height: 5px">
                        <div class="progress-bar bg-primary" role="progressbar" style="width: 66%" aria-valuenow="66" aria-valuemin="0" aria-valuemax="100"></div>
                      </div>
                    </div>
                  </div>
                </div> {% endcomment %}
              </div>
            </div>
          </div>

          <center>
          {% if object.user == request.user or request.user.is_staff%}
          <a href="{% url 'recognizer:update-profile' object.pk %}"><button type="button" class="btn btn-info">Update</button></a>
          <a href="{% url 'recognizer:update-img-profile' object.pk %}"><button type="button" class="btn btn-primary">Update Image</button></a>
          {% else %}{% endif %}

          {% if request.user.is_staff %}
          <a href="{% url 'recognizer:del-profile' object.pk %}"><button type="button" class="btn btn-danger">Delete Profile</button></a>
          {% else %}{% endif %}
          </center>
          </br>
          <br>

        </div>
        
    </div>

{% else %}{% endif %}

    

{% endblock %}

recognizer/templates/recognizer/signup.html
{% extends 'base.html' %}

{% block body_block %}

{% for message in messages %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <b><center>{{ message }}</center> </b>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
{% endfor %}

<center> <h1> Create Account </h1>

<p> Allready have an account, go to <a href="{% url 'recognizer:login' %}">Login</a></center>
<div class='container-sm'>
<form class='form-control' method='POST' >
    {% csrf_token %}
    {{ form.as_p }}
    <input type="hidden" name="next" value="{{ request.GET.next }}"/>
    <input type='submit' class='btn btn-dark'>
</form>
</div>



{% endblock %}